%% Fixed Simulation Problem

% Constants
g = 9.81; % Gravity constant

% Box dimensions
t1 = 0.2; % height of box 1 (m)
l1 = 0.35; % lenght of box 1 (m)

t2 = 0.12; % height of box 2 (m)
l2 = 0.2; % lenght of box 2 (m)

l3o = 0.3; % Initial linear actuator lenght (m)
l3x = l3o + 0.3; % Variable lenght of linear actuator (m) ----------
l2x = (l1 + l2)/2 + l3x; % l2 in function of l3(x) (m)

m1 = 4;   % Mass of box 1 (big box) (kg)
m2 = 2;   % Mass of box 2 (little box) (kg)
m3 = 0; % Mass of the stick (kg) --> Distributed in m1 and m2

% Parameters needed:

% Variables to control
theta = pi/2; % Angle to stabilize the system ------
Fc = 1; % Force applied by servomotor --------

hip = sqrt((t1/2)^2+(l1/2)^2) % hypotenuse for box 1

% Angles needed to calculate the distance 
% for momentum generated by Fcx and Fcy:
beta = asin((t1/2)/hip) 
phi = theta - beta                        

% Distances needed to calculate the 
% momentum generated by Fcx and Fcy:
ay = sin(phi)*hip;
bx = cos(phi)*hip;

% System Forces:
% Fc (Servo force) decomposition
Fcx = Fc *sin(theta); % x component of servomotor force
Fcy = Fc *cos(theta); % y component of servomotor force

% Gravity forces
F1 = -m1 * g
F2 = -m2 * g
F3 = -m3 * g

% Inertia
 I = 10; % -------

% DYNAMICS EQUATIONS:

% X Axis - Force equilibrium
Rx = - Fcx

% Y Axis - Force equilibrium
Ry = F1 + F2 - Fcy

% Mz - Momentum equilibrium
theta_dot_dot = (1/I)*((Fcx*ay) + (Fcy*bx) - (F2*l2x)*cos(theta))

A = [];
















